name: tests
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9, 3.11]
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: bioconda
      - name: Install
        run: |
          conda install paml datrie
          pip install --upgrade pip setuptools wheel
          pip install pytest
          pip install .
      - name: Test
        run: |
          pytest -s --slow

